export const RECEIVE_MESSAGE_RENTING = "AddContract/RECEIVE_MESSAGE_RENTING";
export const RESET_PROPS_RENTING_CONTRACT = "AddContract/RESET_PROPS_RENTING_CONTRACT"
// Add renting contract actions
export const GET_COSTTYPES = "AddContract/GET_COSTTYPES";
export const RECEIVE_COSTTYPES = "AddContract/RECEIVE_COSTTYPES";

// Get renting contracts
export const DEBTOR_RENTING_CONTRACTS_REQUEST_STATUS =
  "DebtorRenting/DEBTOR_RENTING_CONTRACTS_REQUEST_STATUS";
export const GET_DEBTOR_RENTING_CONTRACTS =
  "DebtorRenting/GET_DEBTOR_RENTING_CONTRACTS";
export const RECEIVE_DEBTOR_RENTING_CONTRACTS =
  "DebtorRenting/RECEIVE_DEBTOR_RENTING_CONTRACTS";
export const FETCH_COUNT_DEBTOR_RENTING_CONTRACTS =
  "DebtorRenting/FETCH_COUNT_DEBTOR_RENTING_CONTRACTS";
export const RECEIVE_COUNT_DEBTOR_RENTING_CONTRACTS =
  "DebtorRenting/RECEIVE_COUNT_DEBTOR_RENTING_CONTRACTS";

// Get one
export const GET_DEBTOR_RENTING_CONTRACT =
  "DebtorRenting/GET_DEBTOR_RENTING_CONTRACT";
export const RECEIVE_DEBTOR_RENTING_CONTRACT =
  "DebtorRenting/RECEIVE_DEBTOR_RENTING_CONTRACT";
export const RECEIVE_DEBTOR_RENTING_CONTRACT_LOCATION =
  "DebtorRenting/RECEIVE_DEBTOR_RENTING_CONTRACT_LOCATION";
export const CREATE_DEBTOR_RENTING_CONTRACT =
  "AddContract/CREATE_DEBTOR_RENTING_CONTRACT";
export const UPDATE_DEBTOR_RENTING_CONTRACT =
  "AddContract/UPDATE_DEBTOR_RENTING_CONTRACT";
