/**
 * Employee constants
 */
export const SUBMIT_FORM_DATA = 'SUBMIT_FORM_DATA';
export const RESET_FORM_DATA = 'RESET_FORM_DATA';
export const RECEIVE_MESSAGE_EMPLOYEE = 'RECEIVE_MESSAGE_EMPLOYEE';
export const SET_SHOW_ROW_EMPTY_EMPLOYEE = 'SET_SHOW_ROW_EMPTY_EMPLOYEE';

export const GET_ALL_ROLES = 'GET_ALL_ROLES';
export const RECEIVE_ROLES = 'RECEIVE_ROLES';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const SET_ERRORS_FORM = 'SET_ERRORS_FORM';

export const ADD_ACCOUNT_SUBMIT = 'ADD_ACCOUNT_SUBMIT';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';

export const UPDATE_ACCOUNT_SUBMIT = 'UPDATE_ACCOUNT_SUBMIT';
export const UPDATE_PASSWORD_SUBMIT = 'UPDATE_PASSWORD_SUBMIT';

export const SET_LOADING_GET_DATA = 'SET_LOADING_GET_DATA'