/**
 * Invoice constants
 */

export const RECEIVE_MESSAGE_INVOICE = 'RECEIVE_MESSAGE_INVOICE';
export const COST_CENTER_RECEIVE_MESSAGE_INVOICE = 'COST_CENTER_RECEIVE_MESSAGE_INVOICE';

//COST CENTERS
export const GET_COST_CENTER_ALL = 'GET_COST_CENTER_ALL';
export const RECEIVE_COST_CENTER_ALL = 'RECEIVE_COST_CENTER_ALL';

export const GET_COST_CENTERS = 'GET_COST_CENTERS';
export const RECEIVE_COST_CENTERS = 'RECEIVE_COST_CENTERS';

export const SUBMIT_CREATE_COST_CENTER = 'SUBMIT_CREATE_COST_CENTER';
export const SUBMIT_UPDATE_COST_CENTER = 'SUBMIT_UPDATE_COST_CENTER';

export const CREATE_COST_CENTER = 'CREATE_COST_CENTER';
export const UPDATE_COST_CENTER = 'UPDATE_COST_CENTER';

export const SET_SELECTED_COST_CENTER = 'SET_SELECTED_COST_CENTER';

export const SET_IS_OPEN_ADD_ITEM_MODAL = 'SET_IS_OPEN_ADD_ITEM_MODAL';
// PAGINATION 
export const GET_COSTCENTER_REQUEST_STATUS = 'CostCenter/GET_COSTCENTER_REQUEST_STATUS';
export const FETCH_COUNT_COSTCENTER = 'CostCenter/FETCH_COUNT_COSTCENTER';
export const FETCH_COUNT_COSTCENTER_SUCCESS = 'CostCenter/FETCH_COUNT_COSTCENTER_SUCCESS';

//COST TYPES
export const GET_COST_TYPES = 'GET_COST_TYPES';
export const RECEIVE_COST_TYPES = 'RECEIVE_COST_TYPES';

export const GET_INIT_DATA_COST_TYPE = 'GET_INIT_DATA_COST_TYPE';
export const SET_SELECTED_COST_TYPE = 'SET_SELECTED_COST_TYPE';

export const SUBMIT_CREATE_COST_TYPE = 'SUBMIT_CREATE_COST_TYPE';
export const SUBMIT_UPDATE_COST_TYPE = 'SUBMIT_UPDATE_COST_TYPE';

export const CREATE_COST_TYPE = 'CREATE_COST_TYPE';
export const UPDATE_COST_TYPE = 'UPDATE_COST_TYPE';

export const RECEIVE_LEDGER_ACCOUNTS = 'RECEIVE_LEDGER_ACCOUNTS';
export const RECEIVE_VAT_TYPES = 'RECEIVE_VAT_TYPES';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';

//CUSTOM COST LINES
export const GET_CUSTOM_COST_LINE = 'GET_CUSTOM_COST_LINE';
export const RECEIVE_COST_LINES = 'RECEIVE_COST_LINES';
export const UPDATE_COST_LINE_MUL = 'UPDATE_COST_LINE_MUL';

//REVIEW INVOICES 
export const SUBMIT_GET_REVIEW_INVOICES = 'ReviewInvoice/SUBMIT_GET_REVIEW_INVOICES';
export const GET_REVIEW_INVOICES_REQUEST_STATUS = 'ReviewInvoice/GET_COSTCENTER_REQUEST_STATUS';
export const RECEIVE_REVIEW_INVOICES = 'ReviewInvoice/RECEIVE_REVIEW_INVOICES';

export const SET_SELECTED_REVIEW_INVOICE = 'ReviewInvoice/SET_SELECTED_REVIEW_INVOICE';
export const SUBMIT_CREATE_REVIEW_INVOICES = 'ReviewInvoice/SUBMIT_CREATE_REVIEW_INVOICES';
export const CREATE_REVIEW_INVOICES = "ReviewInvoice/CREATE_REVIEW_INVOICES";

export const GET_DETAIL_INVOICE = 'ReviewInvoice/GET_DETAIL_INVOICE';
export const RECEIVE_DETAIL_INVOICE = 'ReviewInvoice/RECEIVE_DETAIL_INVOICE';
export const SET_RECEIVE_REVIEW_INVOICES = 'ReviewInvoice/SET_RECEIVE_REVIEW_INVOICES';
export const RECEIVE_PARAMS_INVOICES = 'ReviewInvoice/RECEIVE_PARAMS_INVOICES';
export const GET_SELECT_INVOICE = 'ReviewInvoice/GET_SELECT_INVOICE';
export const RECEIVE_SELECT_INVOICE = 'ReviewInvoice/RECEIVE_SELECT_INVOICE';
export const SET_SELECT_INVOICE = 'ReviewInvoice/SET_SELECT_INVOICE';
export const RECEIVE_SELECTED_ROWS = 'ReviewInvoice/RECEIVE_SELECTED_ROWS';



