/**
 * Action types redux
 */
export const GET_LOCATION_ALL = 'Locations/GET_LOCATION_ALL';
export const RECEIVE_LOCATION_ALL = 'Locations/RECEIVE_LOCATION_ALL';
export const GET_LOCATIONS = 'Locations/GET_LOCATIONS';
export const RECEIVE_LOCATIONS = 'Locations/RECEIVE_LOCATIONS';
export const GET_LOCATIONS_REQUEST_STATUS = 'Locations/GET_LOCATIONS_REQUEST_STATUS';

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const LOAD_INIT_DATA = 'LOAD_INIT_DATA';

export const GET_REGIONS = 'GET_REGIONS';
export const RECEIVE_REGIONS = 'RECEIVE_REGIONS';

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';

export const RECEIVE_PERSONS = 'RECEIVE_PERSONS';
export const RECEIVE_GROUPINGS = 'RECEIVE_GROUPINGS';
export const RECEIVE_COSTCENTERS = 'RECEIVE_COSTCENTERS';

export const GET_LOCATION = 'GET_LOCATION';
export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';

export const SUBMIT_CREATE_LOCATION = 'SUBMIT_CREATE_LOCATION';
export const SUBMIT_UPDATE_LOCATION = 'SUBMIT_UPDATE_LOCATION';

export const GET_UNIT = 'InspectionTemplate/GET_UNIT';
export const RECEIVE_UNIT = 'InspectionTemplate/RECEIVE_UNIT';
export const GET_UNIT_REQUEST_STATUS = 'InspectionTemplate/GET_UNIT_REQUEST_STATUS';
export const RESET_GET_UNIT_REQUEST_STATUS = 'InspectionTemplate/RESET_GET_UNIT_REQUEST_STATUS';

export const ADD_INSPECTION = 'ADD_INSPECTION';
export const SUBMITTING_ADD_INSPECTION = 'SUBMITTING_ADD_INSPECTION';
export const SUBMIT_REMOVE_POINT = 'SUBMIT_REMOVE_POINT';

export const REMOVE_INSPECTION = 'REMOVE_INSPECTION';
export const SUCCESS_REMOVE_ALL = 'SUCCESS_REMOVE_ALL';
export const REMOVE_ALL_INSPECTION = 'REMOVE_ALL_INSPECTION';


export const ADD_SELECTED_UNIT = 'ADD_SELECTED_UNIT';
export const UPDATE_SELECTED_UNIT = 'UPDATE_SELECTED_UNIT';

export const COPY_INSPECTION_TEMPLATE = 'COPY_INSPECTION_TEMPLATE';
export const SUCCESS_COPY_INSPECTIONS = 'SUCCESS_COPY_INSPECTIONS';
export const SUBMITTING_COPY_TEMPLATE = 'SUBMITTING_COPY_TEMPLATE';

// PAGINATION ACTION TYPES

export const FETCH_COUNT_LOCATIONS = 'Locations/GET_COUNT_LOCATIONS';
export const FETCH_COUNT_LOCATIONS_SUCCESS = 'Locations/FETCH_COUNT_LOCATIONS_SUCCESS';

/**
 * Contant variables
 */
export const DEFAULT_PROVINCE = 'No Province';