/**
 * People constants
 */

export const GET_PERSONS = 'GET_PERSONS';
export const RECEIVE_PERSONS = 'RECEIVE_PERSONS';

export const GET_PEOPLE_REQUEST_STATUS = 'People/GET_PEOPLE_REQUEST_STATUS';
export const FETCH_COUNT_PEOPLE = 'People/FETCH_COUNT_PEOPLE';
export const FETCH_COUNT_PEOPLE_SUCCESS = 'People/FETCH_COUNT_PEOPLE_SUCCESS';

export const GET_GROUPING_ALL = 'GET_GROUPING_ALL';
export const RECEIVE_GROUPING_ALL = 'RECEIVE_GROUPING_ALL';
export const GET_PERSON_ALL = 'GET_PERSON_ALL';
export const RECEIVE_PERSON_ALL = 'RECEIVE_PERSON_ALL';

export const GET_GROUPINGS = 'GET_GROUPINGS';
export const GET_GROUPING = 'GET_GROUPING';
export const RECEIVE_GROUPING = 'RECEIVE_GROUPING';
export const RECEIVE_GROUPINGS = 'RECEIVE_GROUPINGS';


export const GET_GROUPING_REQUEST_STATUS = 'People/GET_GROUPING_REQUEST_STATUS';
export const FETCH_COUNT_GROUPING = 'People/FETCH_COUNT_GROUPING';
export const FETCH_COUNT_GROUPING_SUCCESS = 'People/FETCH_COUNT_GROUPING_SUCCESS';


export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';
export const RECEIVE_REGIONS = 'RECEIVE_REGIONS';

export const RECEIVE_MESSAGE_CONTACT = 'RECEIVE_MESSAGE_CONTACT';


// CRU Groupings
export const LOAD_INIT_DATA_GROUPING = 'LOAD_INIT_DATA_GROUPING';
export const SUBMIT_CREATE_GROUPING = 'SUBMIT_CREATE_GROUPING';
export const CREATED_GROUPING = 'CREATED_GROUPING';

export const SUBMIT_UPDATE_GROUPING = 'SUBMIT_UPDATE_GROUPING';
export const UPDATED_GROUPING = 'UPDATED_GROUPING';


export const LOAD_INIT_DATA_PERSON = 'LOAD_INIT_DATA_PERSON';
export const GET_PERSON = 'GET_PERSON';
export const RECEIVE_PERSON = 'RECEIVE_PERSON';

export const SUBMIT_CREATE_PERSON = 'SUBMIT_CREATE_PERSON';
export const CREATED_PERSON = 'CREATED_PERSON';

export const SUBMIT_UPDATE_PERSON = 'SUBMIT_UPDATE_PERSON';
export const UPDATED_PERSON = 'UPDATED_PERSON';

export const SET_ERRORS_FORM_GROUPING = 'SET_ERRORS_FORM_GROUPING';

//Debtor contact
export const LOAD_INIT_DATA_DEBTOR_CONTACT = 'LOAD_INIT_DATA_DEBTOR_CONTACT';
export const GET_DEBTOR_CONTACT_LIST = 'GET_DEBTOR_CONTACT_LIST';
export const DEBTOR_CONTACT_REQUEST_STATUS = "DebtorContact/REQUEST_STATUS";

export const RECEIVE_DEBTOR_CONTACTS = 'RECEIVE_DEBTOR_CONTACTS';
export const RECEIVE_DEBTOR_CONTACT = 'RECEIVE_DEBTOR_CONTACT';

export const SUBMIT_CREATE_DEBTOR_CONTACT = 'SUBMIT_CREATE_DEBTOR_CONTACT';
export const SUBMIT_UPDATE_DEBTOR_CONTACT = 'SUBMIT_UPDATE_DEBTOR_CONTACT';

